### ISSUE TITLE
Calendar.java: createICSFile method implementation: takes a File object, creates in on the disk , then adds the icalendar formatting.

### ISSUE THREAD

**Issue by not--p** [Team-Breadfruit/ulu-calendar#4]

**Comment by justinh808** [comment]
In reference to our master branch it looks like we're already doing this exact thing but in the calendar constructor. Therefore we could just add the formatting in the constructor then we wouldn't even need this method.

**Comment by not--p** [comment]
Implemented in commit cacfa545a4fa921384b208af3681be2c6c72d888 (in uluCalendar-dev-jason branch -- to be merged).

**Comment by not--p** [comment]
Please see commit 0f60a8812c59491d2103a9ed809d537fb9af66e5 for perposed closing of this issue.
